### ISSUE TITLE
Cannot login to sulis from new laptop

### ISSUE THREAD

**Issue by hrishitbanerjee** [sulis-hpc/sulis-hpc.github.io#17]
Hi,
I have got a new laptop. I added the id_rsa.pub to safe for this laptop. 
I have Cambridge Chemistry vpn active.
However, I still cannot access Sulis from my new laptop.
Please help.
Thanks and best regards
Hrishit

**Comment by hrishitbanerjee** [comment]
Hi, 
Please could you suggest a solution for this issue?
Thanks and best wishes
Hrishit

**Comment by dquigley533** [comment]
Hi Hrishit,

You've opened this as an issue against the public repository that hosts the Sulis documentation. Presumably you intended to open it against the support-access repository at: https://github.com/sulis-hpc/support-access which is where EPSRC Access to HPC users should raise support queries.

HTH

David
